#read notes at bottom for  forti
version: '3.7' 
services:  
  certbot:
    container_name: 'certbot'
    image: certbot/dns-route53
    restart: "no"
    volumes:
      - ../docker-volumes/etc/letsencrypt:/etc/letsencrypt
      - ../docker-volumes/var/lib/letsencrypt:/var/lib/letsencrypt
      - ../docker-volumes/letsencrypt-docker-nginx/src/letsencrypt/letsencrypt-site:/data/letsencrypt
      - ../docker-volumes/var/log/letsencrypt:/var/log/letsencrypt
      - ../docker-volumes/.aws:/root/.aws 
    command: certonly --email  YOUR-email@YOURDOMAIN.com --agree-tos --no-eff-email --non-interactive -d DOMAIN_NEEDING_CERT.com --dns-route53 --staging 

# create wildcard route53 record. 
#command: certonly --email  You@YOURDomAin.com --agree-tos --no-eff-email --non-interactive -d *.YOURDomAin.com --dns-route53 --staging 

#   docker run -it --rm  -v /mnt/c/Users/rabis/OneDrive/samples/Charming/scripts/cerbot-containerized/docker-volumes/etc/letsencrypt:/etc/letsencrypt -v /mnt/c/Users/rabis/OneDrive/samples/Charming/scripts/cerbot-containerized/docker-volumes/var/lib/letsencrypt:/var/lib/letsencrypt -v /mnt/c/Users/rabis/OneDrive/samples/Charming/scripts/cerbot-containerized/docker-volumes/letsencrypt-docker-nginx/src/letsencrypt/letsencrypt-site:/data/letsencrypt  -v /mnt/c/Users/rabis/OneDrive/samples/Charming/scripts/cerbot-containerized/docker-volumes/var/log/letsencrypt:/var/log/letsencrypt  -v /mnt/c/Users/rabis/OneDrive/samples/Charming/scripts/cerbot-containerized/docker-volumes/.aws:/root/.aws --entrypoint /bin/sh  certbot/dns-route53

# To upload to a fortigate
#Then upload 
#System -> Config -> Certificates -> Import -> Local Certificate. Set type to Certificate. For certificate choose cert.#pem and for key choose privkey.pem
#VPN -> SSL -> Settings. Change Server Certificate.
#Repeat process every 90 days
